apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/k-candidate/gitops-apps.git
    targetRevision: main
    path: manifests/minikube/fastapi-app-prereqs
  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
